name: Hello World

on: [push]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Print Hello World from file
      run: echo "$(cat hello_World.txt)"
